In [3]:
#pandas --> datas
import pandas as pd

Subhra Ghosh (You): How much data (millions of row) can be processed by dataframes?
Hannah Chen: The amount of data that can be processed by pandas DataFrames depends on the available system memory (RAM), data complexity, hardware, and efficiency of your code. Typically, pandas can handle datasets with millions of rows as long as they fit into memory. For larger datasets, consider techniques like chunking, streaming, or distributed computing frameworks. It's best to benchmark and monitor memory usage for your specific use case.

Subhra Ghosh (You): Are all pandas dataframe happens in memory ?
Hannah Chen: Yes, by default, pandas DataFrames are stored in memory.

In [5]:
pd.Series([11,22,33])

0    11
1    22
2    33
dtype: int64

In [6]:
csv_url='https://raw.githubusercontent.com/agconti/kaggle-titanic/master/data/train.csv'

In [9]:
df_csv = pd.read_csv(csv_url)
#default "header = 0" that 1st row is a header

In [10]:
df_csv.head(2)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C

In [12]:
from google.colab import drive

In [13]:
drive.mount('/content/drive')

Mounted at /content/drive

In [15]:
excel_path = '/content/drive/MyDrive/Book1.xlsx'

In [19]:
df_sheet = pd.read_excel(excel_path, sheet_name=0) #sheet_name=0 is 1st tab

In [20]:
df_sheet.head(2)

        1      2       4      5
0     ddd     ff      gg     gg
1  asafsd  sddsf  sdfdsf  fdsfd

In [21]:
dataframe = pd.DataFrame()

In [22]:
#add columns one by one
dataframe['Name'] = ['Lilly','Emma']
dataframe['Age'] =[34,25]
dataframe['Edu'] = ['school','College']

In [23]:
dataframe

    Name  Age      Edu
0  Lilly   34   school
1   Emma   25  College

In [32]:
#Create data dictionary
data_dict = {'Name': ['Subh','Amy'],
        'Age': [29,44],
        'Edu': ['School','College'],
        'Sex': [1,1]
}

In [33]:
dataframe1 = pd.DataFrame(data_dict)
dataframe1

   Name  Age      Edu  Sex
0  Subh   29   School    1
1   Amy   44  College    1

In [37]:
## Get descriptive statistics for any numeric columns
dataframe1.describe()

             Age  Sex
count   2.000000  2.0
mean   36.500000  1.0
std    10.606602  0.0
min    29.000000  1.0
25%    32.750000  1.0
50%    36.500000  1.0
75%    40.250000  1.0
max    44.000000  1.0

In [40]:
#Create data dictionary
datad_dict_2 = {'Name': ['Subh','Amy','Lilly','Emma'],
        'Age': [29,44,22,55],
        'Edu': ['School','College','Phd','College'],
        'Sex': [1,1,0,0]
}

In [66]:
df = pd.DataFrame(data_dict_2)
df

    Name  Age      Edu  Sex
0   Subh   29   School    1
1    Amy   44  College    1
2  Lilly   22      Phd    0
3   Emma   55  College    0

In [50]:
dataframe2 = df2 = pd.DataFrame(data_dict_2,index=['one','two','three','four'])
dataframe2

        Name  Age      Edu  Sex
one     Subh   29   School    1
two      Amy   44  College    1
three  Lilly   22      Phd    0
four    Emma   55  College    0

In [47]:
dataframe2.iloc[0]

Name      Subh
Age         29
Edu     School
Sex          1
Name: one, dtype: object

In [48]:
dataframe2.loc['one'] #same as dataframe2.iloc[0]

Name      Subh
Age         29
Edu     School
Sex          1
Name: one, dtype: object

In [52]:
df2.iloc[:2] #first two rows

     Name  Age      Edu  Sex
one  Subh   29   School    1
two   Amy   44  College    1

In [53]:
dataframe2.loc[0] #will give error as index 0 changed to one
#loc is label based syntax based

KeyError: ignored

In [55]:
df2.iloc[:2,0-+] #first two columns

one    Subh
two     Amy
Name: Name, dtype: object

In [76]:
#three row & two colums
df2.iloc[:2,:3]

     Name  Age      Edu
one  Subh   29   School
two   Amy   44  College

In [74]:
#First Two Rows & Two Colums
df.iloc[:2,:2] # same as df.loc[:2,['Name','Age']]

   Name  Age
0  Subh   29
1   Amy   44

In [77]:
df.loc[:2,['Name','Age']]

    Name  Age
0   Subh   29
1    Amy   44
2  Lilly   22

In [90]:
df.iloc[:2,:3]

   Name  Age      Edu
0  Subh   29   School
1   Amy   44  College

In [59]:
df2['Name'] #returns a series

one       Subh
two        Amy
three    Lilly
four      Emma
Name: Name, dtype: object

In [60]:
df2[['Name']] #returns data table

        Name
one     Subh
two      Amy
three  Lilly
four    Emma

In [98]:
filter = df['Sex'] == 0

KeyError: ignored

In [100]:
df[filter]

    Name  Age      Edu  Gender_Code
2  Lilly   22      Phd            0
3   Emma   55  College            0

In [96]:
df.rename(columns={'Sex':'Gender_Code'},inplace=True)
df

    Name  Age      Edu  Gender_Code
0   Subh   29   School            1
1    Amy   44  College            1
2  Lilly   22      Phd            0
3   Emma   55  College            0

In [101]:
filter = df['Gender_Code'] == 0
filter

0    False
1    False
2     True
3     True
Name: Gender_Code, dtype: bool